# Generated by Django 4.2.3 on 2023-07-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='The name of the category.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='The name of the chef.', max_length=100)),
                ('bio', models.TextField(db_comment='A brief biography or description of the chef.')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='The name of the ingredient.', max_length=100)),
                ('quantity', models.CharField(db_comment='The quantity or amount required.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='The title of the recipe.', max_length=100)),
                ('description', models.TextField(db_comment='A description or instructions for the recipe.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The timestamp when the recipe was created.')),
                ('categories', models.ManyToManyField(db_comment='The categories to which the recipe belongs.', to='recipes.category')),
                ('chef', models.ForeignKey(db_comment='The chef who created the recipe.', on_delete=django.db.models.deletion.CASCADE, to='recipes.chef')),
                ('ingredients', models.ManyToManyField(db_comment='The ingredients required for the recipe.', to='recipes.ingredient')),
            ],
        ),
    ]
